import type {
  CharacterConfig,
  CharacterState,
  CharacterStateConfig,
  CharacterType,
} from './types';

export const CHARACTER_CONFIG: Readonly<Record<CharacterType, CharacterConfig>> = {
  REFRIGERATOR: {
    type: 'REFRIGERATOR',
    slug: 'refrigerator',
    label: 'Buzdolabı',
    silhouette: 'tall',
    primaryColor: '#8ce8ff',
    accentColor: '#6d45f5',
    outlineColor: '#201c35',
    highlightColor: '#ffffff',
    aspectRatio: 0.7,
    gazeLimit: 4,
    features: ['split-door', 'handle'],
  },
  KETTLE: {
    type: 'KETTLE',
    slug: 'kettle',
    label: 'Su ısıtıcısı',
    silhouette: 'round',
    primaryColor: '#ffb64d',
    accentColor: '#6d45f5',
    outlineColor: '#241b30',
    highlightColor: '#fff6df',
    aspectRatio: 0.9,
    gazeLimit: 4,
    features: ['spout', 'kettle-handle'],
  },
  OVEN: {
    type: 'OVEN',
    slug: 'oven',
    label: 'Fırın',
    silhouette: 'box',
    primaryColor: '#ff8a5c',
    accentColor: '#ffd84d',
    outlineColor: '#281c2a',
    highlightColor: '#fff4eb',
    aspectRatio: 0.88,
    gazeLimit: 4,
    features: ['knobs', 'oven-door', 'handle'],
  },
  TELEVISION: {
    type: 'TELEVISION',
    slug: 'television',
    label: 'Televizyon',
    silhouette: 'screen',
    primaryColor: '#6d45f5',
    accentColor: '#80e6ff',
    outlineColor: '#211b35',
    highlightColor: '#f7f5ff',
    aspectRatio: 1.2,
    gazeLimit: 5,
    features: ['screen', 'stand'],
  },
  WASHING_MACHINE: {
    type: 'WASHING_MACHINE',
    slug: 'washing-machine',
    label: 'Çamaşır makinesi',
    silhouette: 'box',
    primaryColor: '#7bdcff',
    accentColor: '#ffcf4a',
    outlineColor: '#1d2238',
    highlightColor: '#f5fcff',
    aspectRatio: 0.86,
    gazeLimit: 4,
    features: ['drum', 'dial'],
  },
  AIR_CONDITIONER: {
    type: 'AIR_CONDITIONER',
    slug: 'air-conditioner',
    label: 'Klima',
    silhouette: 'slim',
    primaryColor: '#9eeaff',
    accentColor: '#4c78ff',
    outlineColor: '#1c2940',
    highlightColor: '#f7fdff',
    aspectRatio: 1.45,
    gazeLimit: 5,
    features: ['vent'],
  },
  MICROWAVE: {
    type: 'MICROWAVE',
    slug: 'microwave',
    label: 'Mikrodalga',
    silhouette: 'box',
    primaryColor: '#b99cff',
    accentColor: '#ffce4a',
    outlineColor: '#251d36',
    highlightColor: '#faf7ff',
    aspectRatio: 1.2,
    gazeLimit: 4,
    features: ['microwave-door', 'keypad'],
  },
  LAMP: {
    type: 'LAMP',
    slug: 'lamp',
    label: 'Aydınlatma',
    silhouette: 'slim',
    primaryColor: '#ffd84d',
    accentColor: '#ff8d4d',
    outlineColor: '#2a2132',
    highlightColor: '#fffbe6',
    aspectRatio: 0.78,
    gazeLimit: 4,
    features: ['shade', 'bulb', 'rays'],
  },
  COMPUTER: {
    type: 'COMPUTER',
    slug: 'computer',
    label: 'Bilgisayar',
    silhouette: 'screen',
    primaryColor: '#65d6bf',
    accentColor: '#6d45f5',
    outlineColor: '#192a32',
    highlightColor: '#f1fffc',
    aspectRatio: 1.18,
    gazeLimit: 5,
    features: ['screen', 'stand', 'keyboard'],
  },
  DISHWASHER: {
    type: 'DISHWASHER',
    slug: 'dishwasher',
    label: 'Bulaşık makinesi',
    silhouette: 'box',
    primaryColor: '#76d9ee',
    accentColor: '#ffb64d',
    outlineColor: '#1d2937',
    highlightColor: '#f5fdff',
    aspectRatio: 0.86,
    gazeLimit: 4,
    features: ['rack', 'handle'],
  },
  HEATER: {
    type: 'HEATER',
    slug: 'heater',
    label: 'Isıtıcı',
    silhouette: 'box',
    primaryColor: '#ff8a5c',
    accentColor: '#ffd84d',
    outlineColor: '#2e1d28',
    highlightColor: '#fff5ed',
    aspectRatio: 0.82,
    gazeLimit: 4,
    features: ['grill', 'dial'],
  },
  VACUUM_CLEANER: {
    type: 'VACUUM_CLEANER',
    slug: 'vacuum-cleaner',
    label: 'Elektrikli süpürge',
    silhouette: 'round',
    primaryColor: '#a886ff',
    accentColor: '#ffcf4a',
    outlineColor: '#251c38',
    highlightColor: '#faf7ff',
    aspectRatio: 1.05,
    gazeLimit: 4,
    features: ['hose', 'dial'],
  },
  SMART_PLUG: {
    type: 'SMART_PLUG',
    slug: 'smart-plug',
    label: 'Akıllı priz',
    silhouette: 'plug',
    primaryColor: '#8ce8d0',
    accentColor: '#6d45f5',
    outlineColor: '#1c2930',
    highlightColor: '#f3fffc',
    aspectRatio: 0.78,
    gazeLimit: 3,
    features: ['prongs', 'socket'],
  },
  IOT_SENSOR: {
    type: 'IOT_SENSOR',
    slug: 'iot-sensor',
    label: 'IoT sensörü',
    silhouette: 'sensor',
    primaryColor: '#7ed8ff',
    accentColor: '#ffcf4a',
    outlineColor: '#1c2638',
    highlightColor: '#f4fbff',
    aspectRatio: 0.92,
    gazeLimit: 4,
    features: ['antenna', 'signal'],
  },
};

export const CHARACTER_STATE_CONFIG: Readonly<Record<CharacterState, CharacterStateConfig>> = {
  idle: {
    state: 'idle',
    label: 'beklemede',
    expression: 'neutral',
    motion: 'breathe',
    urgency: 'none',
  },
  observing: {
    state: 'observing',
    label: 'dikkatle izliyor',
    expression: 'curious',
    motion: 'observe',
    urgency: 'info',
  },
  active: {
    state: 'active',
    label: 'çalışıyor',
    expression: 'focused',
    motion: 'work',
    urgency: 'info',
  },
  sleeping: {
    state: 'sleeping',
    label: 'uyuyor',
    expression: 'sleeping',
    motion: 'sleep',
    urgency: 'none',
  },
  happy: {
    state: 'happy',
    label: 'mutlu',
    expression: 'smile',
    motion: 'bounce',
    urgency: 'positive',
  },
  approved: {
    state: 'approved',
    label: 'onayladı',
    expression: 'proud',
    motion: 'nod',
    urgency: 'positive',
  },
  warning: {
    state: 'warning',
    label: 'uyarı veriyor',
    expression: 'concerned',
    motion: 'worry',
    urgency: 'warning',
  },
  anomalous: {
    state: 'anomalous',
    label: 'anomali algılandı',
    expression: 'alarmed',
    motion: 'alert',
    urgency: 'critical',
  },
  error: {
    state: 'error',
    label: 'bir sorunla karşılaştı',
    expression: 'sad',
    motion: 'shake',
    urgency: 'critical',
  },
  disconnected: {
    state: 'disconnected',
    label: 'bağlantısı kesildi',
    expression: 'offline',
    motion: 'dim',
    urgency: 'warning',
  },
  loading: {
    state: 'loading',
    label: 'yükleniyor',
    expression: 'waiting',
    motion: 'wait',
    urgency: 'info',
  },
  success: {
    state: 'success',
    label: 'işlem başarılı',
    expression: 'celebrating',
    motion: 'celebrate',
    urgency: 'positive',
  },
  privacy: {
    state: 'privacy',
    label: 'gizliliğinizi koruyor',
    expression: 'hidden',
    motion: 'cover',
    urgency: 'none',
  },
};

export function getCharacterConfig(type: CharacterType): CharacterConfig {
  return CHARACTER_CONFIG[type];
}
export function getCharacterStateConfig(state: CharacterState): CharacterStateConfig {
  return CHARACTER_STATE_CONFIG[state];
}
